In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\singh\anaconda3\lib\site-packages (1.4.4)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\singh\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\singh\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.18.5 in c:\users\singh\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: six>=1.5 in c:\users\singh\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

crime = pd.read_csv(r"\Users\singh\Downloads\Crime_Incidents_4271237485119492148.csv")

C:\Users\singh\AppData\Local\Temp\ipykernel_26164\1496755635.py:3: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  crime = pd.read_csv(r"\Users\singh\Downloads\Crime_Incidents_4271237485119492148.csv")

In [3]:
crime

,OBJECTID,PrimaryKey,CaseNumber,District,UCRdesc,OffenseYear,TimeGroup,ReportedDate,OffenseMonth,OffenseDay,...,CENSUS_TRACT,CENSUS_TRACT_GEOID,CENSUS_BLOCK_GROUP,CENSUS_BG_GEOID,CENSUS_BLOCK,CENSUS_BLOCK_GEOID,LAT,LON,x,y
0,1,2.024000e+14,2024-00153213,District 5,Fel Assault,2024,This28,6/1/2024 3:43,5,31,...,Census Tract 1175,39035117500,Block Group 1,3.90351E+11,Block 1003,3.90351E+14,41.556885,-81.568566,-9080171.655,5094833.589
1,2,2.024000e+14,2024-00153587,District 5,Burglary,2024,This28,6/1/2024 12:42,6,1,...,Census Tract 1112.02,39035111202,Block Group 1,3.90351E+11,Block 1018,3.90351E+14,41.528059,-81.631364,-9087162.279,5090546.278
2,3,2.024000e+14,2024-00153139,District 3,Assault,2024,This28,6/1/2024 2:25,5,31,...,Census Tract 1186.02,39035118602,Block Group 2,3.90351E+11,Block 2001,3.90351E+14,41.514356,-81.619666,-9085860.097,5088508.810
3,4,2.024000e+14,2024-00150524,District 4,Assault,2024,This28,5/29/2024 20:41,5,29,...,Census Tract 1159,39035115900,Block Group 3,3.90351E+11,Block 3003,3.90351E+14,41.440774,-81.619782,-9085873.036,5077575.992
4,5,2.024000e+14,2024-00149335,District 3,Theft,2024,This28,5/28/2024 19:31,5,28,...,Census Tract 1984,39035198400,Block Group 2,3.90352E+11,Block 2012,3.90352E+14,41.489449,-81.647251,-9088930.812,5084806.747
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
676989,676990,2.016000e+14,2016-00010728,District 1,Burglary,2016,Older,1/11/2016 15:27,1,9,...,Census Tract 1013,39035101300,Block Group 2,3.90351E+11,Block 2007,3.90351E+14,41.480948,-81.764910,-9102028.577,5083543.482
676990,676991,2.016000e+14,2016-00010118,District O,Assault,2016,Older,1/10/2016 20:41,1,10,...,Census Tract 1974,39035197400,Block Group 2,3.90352E+11,Block 2001,3.90352E+14,41.441018,-81.717836,-9096788.286,5077612.220
676991,676992,2.016000e+14,2016-00009854,District 1,Theft,2016,Older,1/10/2016 16:52,1,10,...,Census Tract 1984,39035198400,Block Group 1,3.90352E+11,Block 1003,3.90352E+14,41.494345,-81.646493,-9088846.452,5085534.423
676992,676993,2.016000e+14,2016-00006867,District 1,Theft,2016,Older,1/7/2016 21:27,1,7,...,Census Tract 1232,39035123200,Block Group 2,3.90351E+11,Block 2005,3.90351E+14,41.469973,-81.789100,-9104721.404,5081912.883
676993,676994,2.016000e+14,2016-00006329,District 3,All Other Offenses,2016,Older,1/7/2016 9:02,1,6,...,Census Tract 1093.01,39035109301,Block Group 1,3.90351E+11,Block 1024,3.90351E+14,41.493408,-81.661592,-9090527.274,5085395.113

In [4]:
cols = ['CENSUS_TRACT', 'CENSUS_TRACT_GEOID', 'CENSUS_BLOCK_GROUP', 'CENSUS_BG_GEOID', 'CENSUS_BLOCK', 'CENSUS_BLOCK_GEOID']

# Loop through each column and count 'Not Located' occurrences
for col in cols:
    count_not_located = (crime[col] == 'Not Located').sum()
    print(f"'{col}' has {count_not_located} 'Not Located' entries")

'CENSUS_TRACT' has 37726 'Not Located' entries
'CENSUS_TRACT_GEOID' has 37726 'Not Located' entries
'CENSUS_BLOCK_GROUP' has 37726 'Not Located' entries
'CENSUS_BG_GEOID' has 37726 'Not Located' entries
'CENSUS_BLOCK' has 37726 'Not Located' entries
'CENSUS_BLOCK_GEOID' has 37726 'Not Located' entries

In [5]:
# PREPROCESSING STEP 1
# handle duplicate and null instances
# remove unnecessary rows
# check for any suprising values

In [6]:
# Check for duplicate entries

duplicate_rows = crime[crime.duplicated()]
duplicate_rows

Empty DataFrame
Columns: [OBJECTID, PrimaryKey, CaseNumber, District, UCRdesc, OffenseYear, TimeGroup, ReportedDate, OffenseMonth, OffenseDay, TimeBlock, DOWname, DOW, HourofDay, DaysAgo, OffenseDate, Statute, City, Zip, StatDesc, Address_Public, WARD, CENSUS_TRACT, CENSUS_TRACT_GEOID, CENSUS_BLOCK_GROUP, CENSUS_BG_GEOID, CENSUS_BLOCK, CENSUS_BLOCK_GEOID, LAT, LON, x, y]
Index: []

[0 rows x 32 columns]

In [7]:
# Look at rows with null entries

rows_with_null = crime[crime.isnull().any(axis=1)]
rows_with_null

,OBJECTID,PrimaryKey,CaseNumber,District,UCRdesc,OffenseYear,TimeGroup,ReportedDate,OffenseMonth,OffenseDay,...,CENSUS_TRACT,CENSUS_TRACT_GEOID,CENSUS_BLOCK_GROUP,CENSUS_BG_GEOID,CENSUS_BLOCK,CENSUS_BLOCK_GEOID,LAT,LON,x,y
62,63,2.024000e+14,2024-00095810,District 5,Robbery,2024,Older,4/10/2024 14:13,4,8,...,Census Tract 1992,39035199200,Block Group 1,3.90352E+11,Block 1013,3.90352E+14,41.538782,-81.615530,-9085399.676,5092140.863
370,371,2.023000e+14,2023-00197057,District 2,Theft,2023,Older,7/2/2023 21:25,6,27,...,Census Tract 1048,39035104800,Block Group 4,3.90351E+11,Block 4000,3.90351E+14,NaN,NaN,NaN,NaN
386,387,2.023000e+14,2023-00186627,District 2,Weapons,2023,Older,6/24/2023 5:09,6,24,...,Census Tract 1027,39035102700,Block Group 2,3.90351E+11,Block 2007,3.90351E+14,41.467516,-81.720570,-9097092.676,5081547.868
534,535,2.021000e+14,2021-00054565,District O,Assault,2021,Older,2/24/2021 15:06,2,24,...,Census Tract 1087.01,39035108701,Block Group 3,3.90351E+11,Block 3009,3.90351E+14,NaN,NaN,NaN,NaN
627,628,2.020000e+14,2020-00384851,District 3,Assault,2020,Older,12/9/2020 17:24,12,9,...,Census Tract 1189,39035118900,Block Group 2,3.90351E+11,Block 2001,3.90351E+14,41.509664,-81.621668,-9086082.955,5087811.348
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
676970,676971,2.016000e+14,2016-00030757,District O,Fel Assault,2016,Older,1/31/2016 7:58,1,31,...,Census Tract 1087.01,39035108701,Block Group 3,3.90351E+11,Block 3009,3.90351E+14,41.492897,-81.655332,-9089830.447,5085319.102
676974,676975,2.016000e+14,2016-00026692,District 2,Vandalism,2016,Older,1/27/2016 17:09,1,25,...,Census Tract 1053,39035105300,Block Group 2,3.90351E+11,Block 2001,3.90351E+14,41.458177,-81.713326,-9096286.251,5080160.517
676975,676976,2.016000e+14,2016-00026570,District 4,Drug Abuse Violations,2016,Older,1/27/2016 15:06,1,27,...,Census Tract 1211,39035121100,Block Group 1,3.90351E+11,Block 1006,3.90351E+14,41.455710,-81.591162,-9082687.041,5079794.147
676981,676982,2.016000e+14,2016-00017721,District 3,Assault,2016,Older,1/18/2016 12:07,1,16,...,Census Tract 1084,39035108400,Block Group 1,3.90351E+11,Block 1011,3.90351E+14,41.512440,-81.665739,-9090988.917,5088224.024
676989,676990,2.016000e+14,2016-00010728,District 1,Burglary,2016,Older,1/11/2016 15:27,1,9,...,Census Tract 1013,39035101300,Block Group 2,3.90351E+11,Block 2007,3.90351E+14,41.480948,-81.764910,-9102028.577,5083543.482

In [8]:
# We can see here that there are significantly less LAT and LON values in the rows with null entries. LAT and LON are crucial for our model
# So, remove ONLY the entries with null LAT and LON values first

rows_with_null.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 56706 entries, 62 to 676989
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   OBJECTID            56706 non-null  int64
 1   PrimaryKey          56706 non-null  float64
 2   CaseNumber          56706 non-null  object
 3   District            56706 non-null  object
 4   UCRdesc             56706 non-null  object
 5   OffenseYear         56706 non-null  int64
 6   TimeGroup           56706 non-null  object
 7   ReportedDate        56706 non-null  object
 8   OffenseMonth        56706 non-null  int64
 9   OffenseDay          56706 non-null  int64
 10  TimeBlock           56706 non-null  object
 11  DOWname             56706 non-null  object
 12  DOW                 56706 non-null  int64
 13  HourofDay           56706 non-null  int64
 14  DaysAgo             56706 non-null  int64
 15  OffenseDate         56706 non-null  object
 16  Statute             56706 non-null  object
 17  City                26474 non-null  object
 18  Zip                 7476 non-null   object
 19  StatDesc            56706 non-null  object
 20  Address_Public      55323 non-null  object
 21  WARD                56706 non-null  object
 22  CENSUS_TRACT        56706 non-null  object
 23  CENSUS_TRACT_GEOID  56706 non-null  object
 24  CENSUS_BLOCK_GROUP  56706 non-null  object
 25  CENSUS_BG_GEOID     56706 non-null  object
 26  CENSUS_BLOCK        56706 non-null  object
 27  CENSUS_BLOCK_GEOID  56706 non-null  object
 28  LAT                 19823 non-null  float64
 29  LON                 19823 non-null  float64
 30  x                   19823 non-null  float64
 31  y                   19823 non-null  float64
dtypes: float64(5), int64(7), object(20)
memory usage: 14.3+ MB

In [9]:
# Remove the entries with empty LAT and LON values

crime = crime.dropna(subset=['LAT', 'LON'])

In [10]:
# Now, LAT and LON are no longer a problem
# Entries with an empty value do not have LAT and LON as empty

rows_with_null = crime[crime.isnull().any(axis=1)]
rows_with_null.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19823 entries, 62 to 676989
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   OBJECTID            19823 non-null  int64
 1   PrimaryKey          19823 non-null  float64
 2   CaseNumber          19823 non-null  object
 3   District            19823 non-null  object
 4   UCRdesc             19823 non-null  object
 5   OffenseYear         19823 non-null  int64
 6   TimeGroup           19823 non-null  object
 7   ReportedDate        19823 non-null  object
 8   OffenseMonth        19823 non-null  int64
 9   OffenseDay          19823 non-null  int64
 10  TimeBlock           19823 non-null  object
 11  DOWname             19823 non-null  object
 12  DOW                 19823 non-null  int64
 13  HourofDay           19823 non-null  int64
 14  DaysAgo             19823 non-null  int64
 15  OffenseDate         19823 non-null  object
 16  Statute             19823 non-null  object
 17  City                18540 non-null  object
 18  Zip                 1281 non-null   object
 19  StatDesc            19823 non-null  object
 20  Address_Public      19823 non-null  object
 21  WARD                19823 non-null  object
 22  CENSUS_TRACT        19823 non-null  object
 23  CENSUS_TRACT_GEOID  19823 non-null  object
 24  CENSUS_BLOCK_GROUP  19823 non-null  object
 25  CENSUS_BG_GEOID     19823 non-null  object
 26  CENSUS_BLOCK        19823 non-null  object
 27  CENSUS_BLOCK_GEOID  19823 non-null  object
 28  LAT                 19823 non-null  float64
 29  LON                 19823 non-null  float64
 30  x                   19823 non-null  float64
 31  y                   19823 non-null  float64
dtypes: float64(5), int64(7), object(20)
memory usage: 5.0+ MB

In [11]:
# Only use entries from years between 2018-2022 (Census data is for those years)
# Years before do not have enough values

crime = crime[(crime['OffenseYear'] > 2017) & (crime['OffenseYear'] < 2023)]
crime

,OBJECTID,PrimaryKey,CaseNumber,District,UCRdesc,OffenseYear,TimeGroup,ReportedDate,OffenseMonth,OffenseDay,...,CENSUS_TRACT,CENSUS_TRACT_GEOID,CENSUS_BLOCK_GROUP,CENSUS_BG_GEOID,CENSUS_BLOCK,CENSUS_BLOCK_GEOID,LAT,LON,x,y
15,16,2.021000e+14,2021-00167894,District 1,Fraud,2021,Older,6/5/2021 4:41,6,4,...,Census Tract 1013,39035101300,Block Group 2,3.90351E+11,Block 2000,3.90351E+14,41.483143,-81.766893,-9102249.361,5083869.648
16,17,2.022000e+14,2022-00172806,District 2,Assault,2022,Older,6/18/2022 22:52,6,18,...,Census Tract 1070,39035107000,Block Group 2,3.90351E+11,Block 2004,3.90351E+14,41.434211,-81.683311,-9092944.969,5076601.388
303,304,2.023000e+14,2023-00259552,District 5,Fraud,2020,Older,8/23/2023 23:35,8,8,...,Census Tract 1176,39035117600,Block Group 3,3.90351E+11,Block 3001,3.90351E+14,41.579019,-81.556672,-9078847.680,5098126.906
306,307,2.020000e+14,2020-00177873,District 4,Vandalism,2020,Older,6/18/2020 7:26,6,18,...,Census Tract 1221,39035122100,Block Group 2,3.90351E+11,Block 2002,3.90351E+14,41.449064,-81.564849,-9079757.889,5078807.032
404,405,2.022000e+14,2022-00172167,District 5,Fel Assault,2022,Older,6/18/2022 8:22,6,18,...,Census Tract 1117,39035111700,Block Group 1,3.90351E+11,Block 1000,3.90351E+14,41.530355,-81.634045,-9087460.803,5090887.626
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
676491,676492,2.022000e+14,2022-00086102,District 5,Drug Abuse Violations,2022,Older,3/30/2022 19:38,3,30,...,Not Located,Not Located,Not Located,Not Located,Not Located,Not Located,41.501102,-81.487301,-9071125.280,5086538.681
676509,676510,2.021000e+14,2021-00307549,District 4,Weapons,2021,Older,10/5/2021 12:39,10,5,...,Not Located,Not Located,Not Located,Not Located,Not Located,Not Located,41.429426,-81.612709,-9085085.627,5075890.995
676519,676520,2.021000e+14,2021-00155951,District 3,All Other Offenses,2021,Older,5/26/2021 1:42,5,25,...,Not Located,Not Located,Not Located,Not Located,Not Located,Not Located,41.379334,-81.528461,-9075707.203,5068456.565
676562,676563,2.019000e+14,2019-00361663,District 5,Vandalism,2019,Older,11/24/2019 21:35,11,16,...,Not Located,Not Located,Not Located,Not Located,Not Located,Not Located,41.567861,-81.585252,-9082029.143,5096466.526
676572,676573,2.019000e+14,2019-00295988,District 4,Drug Abuse Violations,2019,Older,9/24/2019 18:33,9,24,...,Not Located,Not Located,Not Located,Not Located,Not Located,Not Located,41.434184,-81.630703,-9087088.725,5076597.389

In [12]:
# Save a version of dataframe for temporal and spatial pattern exploration

crime.to_csv("crime_preprocessed_exploration", index=False)

In [13]:
# Now, let's think about what attributes we don't need to trian our model
# Model is soley based on LAT and LON, so we can remove all other geographic identifiers
# IMPORTANT: We will remove Census tracts for now, but if we want economic/socioeconomic data we can add an attribute back

cols = ['City', 'Zip', 'Address_Public', 'WARD', 'x', 'y']
crime = crime.drop(columns=cols)
crime.shape[0]

376042

In [14]:
# No, empty values anywhere now

rows_with_null = crime[crime.isnull().any(axis=1)]
rows_with_null.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   OBJECTID            0 non-null      int64
 1   PrimaryKey          0 non-null      float64
 2   CaseNumber          0 non-null      object
 3   District            0 non-null      object
 4   UCRdesc             0 non-null      object
 5   OffenseYear         0 non-null      int64
 6   TimeGroup           0 non-null      object
 7   ReportedDate        0 non-null      object
 8   OffenseMonth        0 non-null      int64
 9   OffenseDay          0 non-null      int64
 10  TimeBlock           0 non-null      object
 11  DOWname             0 non-null      object
 12  DOW                 0 non-null      int64
 13  HourofDay           0 non-null      int64
 14  DaysAgo             0 non-null      int64
 15  OffenseDate         0 non-null      object
 16  Statute             0 non-null      object
 17  StatDesc            0 non-null      object
 18  CENSUS_TRACT        0 non-null      object
 19  CENSUS_TRACT_GEOID  0 non-null      object
 20  CENSUS_BLOCK_GROUP  0 non-null      object
 21  CENSUS_BG_GEOID     0 non-null      object
 22  CENSUS_BLOCK        0 non-null      object
 23  CENSUS_BLOCK_GEOID  0 non-null      object
 24  LAT                 0 non-null      float64
 25  LON                 0 non-null      float64
dtypes: float64(3), int64(7), object(16)
memory usage: 0.0+ bytes

In [15]:
# We now have a "complete" dataset

crime.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 376042 entries, 15 to 676572
Data columns (total 26 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   OBJECTID            376042 non-null  int64
 1   PrimaryKey          376042 non-null  float64
 2   CaseNumber          376042 non-null  object
 3   District            376042 non-null  object
 4   UCRdesc             376042 non-null  object
 5   OffenseYear         376042 non-null  int64
 6   TimeGroup           376042 non-null  object
 7   ReportedDate        376042 non-null  object
 8   OffenseMonth        376042 non-null  int64
 9   OffenseDay          376042 non-null  int64
 10  TimeBlock           376042 non-null  object
 11  DOWname             376042 non-null  object
 12  DOW                 376042 non-null  int64
 13  HourofDay           376042 non-null  int64
 14  DaysAgo             376042 non-null  int64
 15  OffenseDate         376042 non-null  object
 16  Statute             376042 non-null  object
 17  StatDesc            376042 non-null  object
 18  CENSUS_TRACT        376042 non-null  object
 19  CENSUS_TRACT_GEOID  376042 non-null  object
 20  CENSUS_BLOCK_GROUP  376042 non-null  object
 21  CENSUS_BG_GEOID     376042 non-null  object
 22  CENSUS_BLOCK        376042 non-null  object
 23  CENSUS_BLOCK_GEOID  376042 non-null  object
 24  LAT                 376042 non-null  float64
 25  LON                 376042 non-null  float64
dtypes: float64(3), int64(7), object(16)
memory usage: 77.5+ MB

In [16]:
# Remove the columns we do not need

cols = ['OBJECTID', 'PrimaryKey', 'CaseNumber', 'District', 'ReportedDate', 'DOWname', 'Statute', 'StatDesc', 'TimeGroup']
crime = crime.drop(columns=cols)
crime.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 376042 entries, 15 to 676572
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   UCRdesc             376042 non-null  object
 1   OffenseYear         376042 non-null  int64
 2   OffenseMonth        376042 non-null  int64
 3   OffenseDay          376042 non-null  int64
 4   TimeBlock           376042 non-null  object
 5   DOW                 376042 non-null  int64
 6   HourofDay           376042 non-null  int64
 7   DaysAgo             376042 non-null  int64
 8   OffenseDate         376042 non-null  object
 9   CENSUS_TRACT        376042 non-null  object
 10  CENSUS_TRACT_GEOID  376042 non-null  object
 11  CENSUS_BLOCK_GROUP  376042 non-null  object
 12  CENSUS_BG_GEOID     376042 non-null  object
 13  CENSUS_BLOCK        376042 non-null  object
 14  CENSUS_BLOCK_GEOID  376042 non-null  object
 15  LAT                 376042 non-null  float64
 16  LON                 376042 non-null  float64
dtypes: float64(2), int64(6), object(9)
memory usage: 51.6+ MB

In [18]:
# Let's take a deeper look into each of the attribute to make sure the data has no gaps or surprises

for col in crime.columns:
    print(crime[col].unique())
    print("\n")

['Fraud' 'Assault' 'Vandalism' 'Fel Assault' 'Theft' 'Weapons'
 'All Other Offenses' 'Offense Against Family/Children' 'Robbery' 'GTMV'
 'Drug Abuse Violations' 'Burglary' 'Driving Under The Influence'
 'Sex Offenses' 'Arson' 'Forgery & Counterfeiting' 'Embezzlement'
 'Stolen Property' 'Disorderly Conduct' 'Rape' 'Drunkenness' 'Liquor Laws'
 'Homicide' 'Property Damaged' 'Prostitution' 'Traffic Violations' '1C'
 'Gambling']


[2021 2022 2020 2018 2019]


[ 6  8  5  4  1  3  2 12 10 11  7  9]


[ 4 18  8 17 13 16 15  9  1 30 11 27 26 25 23 24 14 12 10  7  2 29 28 20
 22 19  6  5  3 21 31]


['Early Night' 'Day' 'Morning' 'Night']


[6 7 5 3 4 2 1]


[23 17  8  2  3 22  0 12 11  4 19 21 10  7 20  1 15  5  6 16 18 14 13  9]


[1101  722 1401 ... 2154 2219 2146]


['6/5/2021 4:41' '6/18/2022 22:23' '8/8/2020 13:00' ... '1/19/2018 21:42'
 '1/11/2018 5:30' '1/1/2018 6:58']


['Census Tract 1013' 'Census Tract 1070' 'Census Tract 1176'
 'Census Tract 1221' 'Census Tract 1117' 'Census Tract 1275.01'
 'Census Tract 1979' 'Census Tract 1980' 'Census Tract 1239'
 'Census Tract 1114.01' 'Census Tract 1093.01' 'Census Tract 1215'
 'Census Tract 1051' 'Census Tract 1175' 'Census Tract 1214.03'
 'Census Tract 1172.01' 'Census Tract 1235.01' 'Census Tract 1078.02'
 'Census Tract 1207.01' 'Census Tract 1053' 'Census Tract 1178'
 'Census Tract 1055' 'Census Tract 1036.02' 'Census Tract 1154'
 'Census Tract 1232' 'Census Tract 1218' 'Census Tract 1022'
 'Census Tract 1077.01' 'Census Tract 1978' 'Census Tract 1245'
 'Census Tract 1196' 'Census Tract 1204' 'Census Tract 1188'
 'Census Tract 1035' 'Census Tract 1087.01' 'Census Tract 1165'
 'Census Tract 1207.02' 'Census Tract 1987' 'Census Tract 1984'
 'Census Tract 1066' 'Census Tract 1985' 'Census Tract 1171.01'
 'Census Tract 1097.01' 'Census Tract 1069' 'Census Tract 9805'
 'Census Tract 1021.01' 'Census Tract 1241' 'Census Tract 1202'
 'Census Tract 1968' 'Census Tract 1243' 'Census Tract 1211'
 'Census Tract 1024.01' 'Census Tract 1992' 'Census Tract 1121'
 'Census Tract 1198' 'Census Tract 1972' 'Census Tract 1016.03'
 'Census Tract 1057' 'Census Tract 1159' 'Census Tract 1056.02'
 'Census Tract 1183.01' 'Census Tract 1068' 'Census Tract 1205'
 'Census Tract 1990' 'Census Tract 1027' 'Census Tract 1018'
 'Census Tract 1014' 'Census Tract 1964' 'Census Tract 1991'
 'Census Tract 1082.01' 'Census Tract 1219' 'Census Tract 1213'
 'Census Tract 1061' 'Census Tract 1208.02' 'Census Tract 1236.03'
 'Census Tract 1195.01' 'Census Tract 1208.01' 'Census Tract 1212'
 'Census Tract 1989' 'Census Tract 1977' 'Census Tract 1168'
 'Census Tract 1186.02' 'Census Tract 1986' 'Census Tract 1223'
 'Census Tract 1084' 'Census Tract 1171.02' 'Census Tract 1166'
 'Census Tract 1011.02' 'Census Tract 1235.02' 'Census Tract 1028'
 'Census Tract 1981' 'Census Tract 1054' 'Census Tract 1167'
 'Census Tract 1062' 'Census Tract 1179' 'Census Tract 1033'
 'Census Tract 1197.01' 'Census Tract 1242.02' 'Census Tract 1974'
 'Census Tract 1148' 'Census Tract 1071.01' 'Census Tract 1164'
 'Census Tract 1024.02' 'Census Tract 1122' 'Census Tract 1174'
 'Census Tract 1109.01' 'Census Tract 1015.01' 'Census Tract 1169'
 'Census Tract 1181.01' 'Census Tract 1059' 'Census Tract 1017'
 'Census Tract 1988' 'Census Tract 1189' 'Census Tract 1246'
 'Census Tract 1182' 'Census Tract 1975' 'Census Tract 1242.01'
 'Census Tract 1237' 'Census Tract 1029' 'Census Tract 1083.01'
 'Census Tract 1199' 'Census Tract 1012.01' 'Census Tract 1023'
 'Census Tract 1206' 'Census Tract 1145.01' 'Census Tract 1019.01'
 'Census Tract 1011.01' 'Census Tract 1098.01' 'Census Tract 1173'
 'Census Tract 1038' 'Census Tract 1048' 'Census Tract 1157'
 'Census Tract 1021.02' 'Census Tract 1236.02' 'Census Tract 1158'
 'Census Tract 1231' 'Census Tract 1172.03' 'Census Tract 1976'
 'Census Tract 1197.02' 'Census Tract 1044' 'Census Tract 1222'
 'Census Tract 1112.02' 'Census Tract 1217' 'Census Tract 1261'
 'Census Tract 1146' 'Census Tract 1194.02' 'Census Tract 1195.02'
 'Census Tract 9801' 'Census Tract 1065' 'Census Tract 1238'
 'Census Tract 1234' 'Census Tract 1177' 'Census Tract 1214.01'
 'Census Tract 1163' 'Census Tract 1194.01' 'Census Tract 9802'
 'Census Tract 1236.01' 'Census Tract 1123.01' 'Not Located'
 'Census Tract 1525.01' 'Census Tract 1961' 'Census Tract 9809'
 'Census Tract 1993' 'Census Tract 1521.01' 'Census Tract 9811'
 'Census Tract 1411' 'Census Tract 1524' 'Census Tract 1773.03'
 'Census Tract 1771.04' 'Census Tract 1772.02' 'Census Tract 1381.09'
 'Census Tract 1928' 'Census Tract 1501' 'Census Tract 1371.01'
 'Census Tract 1970' 'Census Tract 1982' 'Census Tract 1518'
 'Census Tract 1512']


['39035101300' '39035107000' '39035117600' '39035122100' '39035111700'
 '39035127501' '39035197900' '39035198000' '39035123900' '39035111401'
 '39035109301' '39035121500' '39035105100' '39035117500' '39035121403'
 '39035117201' '39035123501' '39035107802' '39035120701' '39035105300'
 '39035117800' '39035105500' '39035103602' '39035115400' '39035123200'
 '39035121800' '39035102200' '39035107701' '39035197800' '39035124500'
 '39035119600' '39035120400' '39035118800' '39035103500' '39035108701'
 '39035116500' '39035120702' '39035198700' '39035198400' '39035106600'
 '39035198500' '39035117101' '39035109701' '39035106900' '39035980500'
 '39035102101' '39035124100' '39035120200' '39035196800' '39035124300'
 '39035121100' '39035102401' '39035199200' '39035112100' '39035119800'
 '39035197200' '39035101603' '39035105700' '39035115900' '39035105602'
 '39035118301' '39035106800' '39035120500' '39035199000' '39035102700'
 '39035101800' '39035101400' '39035196400' '39035199100' '39035108201'
 '39035121900' '39035121300' '39035106100' '39035120802' '39035123603'
 '39035119501' '39035120801' '39035121200' '39035198900' '39035197700'
 '39035116800' '39035118602' '39035198600' '39035122300' '39035108400'
 '39035117102' '39035116600' '39035101102' '39035123502' '39035102800'
 '39035198100' '39035105400' '39035116700' '39035106200' '39035117900'
 '39035103300' '39035119701' '39035124202' '39035197400' '39035114800'
 '39035107101' '39035116400' '39035102402' '39035112200' '39035117400'
 '39035110901' '39035101501' '39035116900' '39035118101' '39035105900'
 '39035101700' '39035198800' '39035118900' '39035124600' '39035118200'
 '39035197500' '39035124201' '39035123700' '39035102900' '39035108301'
 '39035119900' '39035101201' '39035102300' '39035120600' '39035114501'
 '39035101901' '39035101101' '39035109801' '39035117300' '39035103800'
 '39035104800' '39035115700' '39035102102' '39035123602' '39035115800'
 '39035123100' '39035117203' '39035197600' '39035119702' '39035104400'
 '39035122200' '39035111202' '39035121700' '39035126100' '39035114600'
 '39035119402' '39035119502' '39035980100' '39035106500' '39035123800'
 '39035123400' '39035117700' '39035121401' '39035116300' '39035119401'
 '39035980200' '39035123601' '39035112301' 'Not Located' '39035152501'
 '39035196100' '39035980900' '39035199300' '39035152101' '39035981100'
 '39035141100' '39035152400' '39035177303' '39035177104' '39035177202'
 '39035138109' '39035192800' '39035150100' '39035137101' '39035197000'
 '39035198200' '39035151800' '39035151200']


['Block Group 2' 'Block Group 3' 'Block Group 1' 'Block Group 4'
 'Block Group 5' 'Block Group 6' 'Not Located']


['3.90351E+11' '3.90352E+11' '3.9036E+11' 'Not Located']


['Block 2000' 'Block 2004' 'Block 3001' 'Block 2002' 'Block 1000'
 'Block 3004' 'Block 3000' 'Block 2008' 'Block 2003' 'Block 1004'
 'Block 1005' 'Block 2001' 'Block 4003' 'Block 1029' 'Block 2014'
 'Block 4008' 'Block 1019' 'Block 2024' 'Block 1022' 'Block 1007'
 'Block 2005' 'Block 1006' 'Block 4001' 'Block 3015' 'Block 2020'
 'Block 2039' 'Block 2017' 'Block 3010' 'Block 3006' 'Block 1028'
 'Block 1002' 'Block 1020' 'Block 1001' 'Block 2011' 'Block 1012'
 'Block 3014' 'Block 1010' 'Block 2016' 'Block 3007' 'Block 1015'
 'Block 3019' 'Block 3008' 'Block 2007' 'Block 1013' 'Block 3009'
 'Block 3002' 'Block 1003' 'Block 1008' 'Block 1009' 'Block 2062'
 'Block 5001' 'Block 2019' 'Block 2010' 'Block 2009' 'Block 3003'
 'Block 3012' 'Block 2006' 'Block 5015' 'Block 4000' 'Block 4004'
 'Block 1011' 'Block 1040' 'Block 2034' 'Block 4007' 'Block 4009'
 'Block 2013' 'Block 3018' 'Block 1023' 'Block 1038' 'Block 4011'
 'Block 2012' 'Block 1024' 'Block 1025' 'Block 1016' 'Block 1035'
 'Block 4006' 'Block 1018' 'Block 5008' 'Block 3021' 'Block 2026'
 'Block 3005' 'Block 3011' 'Block 1027' 'Block 1030' 'Block 2021'
 'Block 4012' 'Block 4013' 'Block 3031' 'Block 5012' 'Block 1017'
 'Block 1026' 'Block 4015' 'Block 2032' 'Block 1032' 'Block 1042'
 'Block 1043' 'Block 3025' 'Block 4010' 'Block 1014' 'Block 1021'
 'Block 4005' 'Block 5009' 'Block 4002' 'Block 1039' 'Block 1062'
 'Block 1037' 'Block 3013' 'Block 2025' 'Block 4014' 'Block 1034'
 'Block 3035' 'Block 2015' 'Block 2054' 'Block 5010' 'Block 1036'
 'Block 2023' 'Block 3016' 'Block 3027' 'Block 2051' 'Block 4022'
 'Block 2031' 'Block 2022' 'Block 1031' 'Block 2027' 'Block 5000'
 'Block 6006' 'Block 4021' 'Block 5013' 'Block 4025' 'Block 3030'
 'Block 2044' 'Block 2018' 'Block 5011' 'Block 4018' 'Block 2040'
 'Block 5003' 'Block 6001' 'Block 2038' 'Block 5018' 'Block 5017'
 'Block 2029' 'Block 2050' 'Block 1033' 'Block 2047' 'Block 1041'
 'Block 1045' 'Block 4017' 'Block 5002' 'Block 4020' 'Block 5004'
 'Block 5014' 'Block 3034' 'Block 3020' 'Block 2063' 'Block 3051'
 'Block 2028' 'Block 1044' 'Not Located' 'Block 3038' 'Block 2035'
 'Block 3032' 'Block 3047' 'Block 1048' 'Block 3022' 'Block 3042'
 'Block 3046' 'Block 4016' 'Block 2036' 'Block 4024' 'Block 5006'
 'Block 3029' 'Block 3017' 'Block 1050' 'Block 3044' 'Block 2043'
 'Block 3023' 'Block 1070' 'Block 1046' 'Block 2030' 'Block 1069'
 'Block 6004' 'Block 3024' 'Block 3048' 'Block 2037' 'Block 1053'
 'Block 5019' 'Block 3028' 'Block 1049' 'Block 6003' 'Block 3052'
 'Block 4023' 'Block 1051' 'Block 3050' 'Block 4019' 'Block 1066'
 'Block 5007' 'Block 2048' 'Block 1072' 'Block 3058' 'Block 3033'
 'Block 2041' 'Block 5005' 'Block 2033' 'Block 4026' 'Block 1052'
 'Block 3045' 'Block 3037' 'Block 2046' 'Block 3049' 'Block 6002'
 'Block 2045' 'Block 3026' 'Block 1059' 'Block 1071' 'Block 6005'
 'Block 3043' 'Block 3040' 'Block 6000' 'Block 1047' 'Block 2053'
 'Block 3041' 'Block 1058' 'Block 2061' 'Block 3039' 'Block 3057'
 'Block 1073' 'Block 2056' 'Block 2042' 'Block 1068' 'Block 1054'
 'Block 3036' 'Block 3059' 'Block 3054' 'Block 2058' 'Block 3055'
 'Block 3053' 'Block 1067' 'Block 3056' 'Block 2055']


['3.90351E+14' '3.90352E+14' '3.9036E+14' 'Not Located']


[41.48314284 41.43421094 41.57901933 ... 41.48328246 41.46460462
 41.3793339 ]


[-81.76689326 -81.68331052 -81.55667244 ... -81.71797013 -81.78297127
 -81.52846108]

In [19]:
# Everything looks good...but let's just make sure that our crucial LAT and LON don't have any non-numeric vales

cols = ['LAT', 'LON']
non_numeric = crime[cols].apply(pd.to_numeric, errors='coerce')
non_numeric_rows = crime[non_numeric.isnull().any(axis=1)]
print(non_numeric_rows)

Empty DataFrame
Columns: [UCRdesc, OffenseYear, OffenseMonth, OffenseDay, TimeBlock, DOW, HourofDay, DaysAgo, OffenseDate, CENSUS_TRACT, CENSUS_TRACT_GEOID, CENSUS_BLOCK_GROUP, CENSUS_BG_GEOID, CENSUS_BLOCK, CENSUS_BLOCK_GEOID, LAT, LON]
Index: []

In [20]:
# END OF PREPROCESSING STEP 1
# check for duplicates
# remove null values
# remove unnecessary rows
# make sure there are no suprising values for any attribute

In [21]:
# PREPROCESSING STEP 2
# make data ready for model entry
# handle non-numerical data

In [22]:
crime.columns

Index(['UCRdesc', 'OffenseYear', 'OffenseMonth', 'OffenseDay', 'TimeBlock',
       'DOW', 'HourofDay', 'DaysAgo', 'OffenseDate', 'CENSUS_TRACT',
       'CENSUS_TRACT_GEOID', 'CENSUS_BLOCK_GROUP', 'CENSUS_BG_GEOID',
       'CENSUS_BLOCK', 'CENSUS_BLOCK_GEOID', 'LAT', 'LON'],
      dtype='object')

In [23]:
# There is are discrepancies between the 'OffenseMonth', 'OffenseDay' and 'OffenseDate'

# Assuming 'OffenseDate' is a datetime string, convert it to a datetime object
crime['OffenseDate'] = pd.to_datetime(crime['OffenseDate'], errors='coerce')

# Extract month and day from the 'OffenseDate' column
crime['ExtractedMonth'] = crime['OffenseDate'].dt.month
crime['ExtractedDay'] = crime['OffenseDate'].dt.day

# Identify rows where OffenseMonth/OffenseDay and OffenseDate don't match
inconsistent_records = crime[(crime['OffenseMonth'] != crime['ExtractedMonth']) | (crime['OffenseDay'] != crime['ExtractedDay'])]

In [24]:
# There are inconsistencies so, we will remove 'OffenseMonth' & 'OffenseDay'
# and use the 'ExtractedMonth' and 'ExtractedDay' attributes instead

inconsistent_records.shape[0]

91842

In [25]:
# Drop no longer needed attributes, make OffenseDate YYYY:MM:DD

crime = crime.drop(columns=['OffenseMonth', 'OffenseDay'])
crime['OffenseDate'] = pd.to_datetime(crime['OffenseDate'])

In [26]:
# Use a label encoder to create dictionaries that map our non-numeric values
# to numeric values

from sklearn.preprocessing import LabelEncoder

mappings = {}

cols = ['UCRdesc', 'OffenseYear', 'TimeBlock']
for col in cols:
    le = LabelEncoder()
    crime[col + '_numeric'] = le.fit_transform(crime[col])
    
    mappings[col] = dict(zip(le.classes_, le.transform(le.classes_)))
    
for col, mapping in mappings.items():
    print(f"{col}: {mapping}")
    print("\n")

UCRdesc: {'1C': 0, 'All Other Offenses': 1, 'Arson': 2, 'Assault': 3, 'Burglary': 4, 'Disorderly Conduct': 5, 'Driving Under The Influence': 6, 'Drug Abuse Violations': 7, 'Drunkenness': 8, 'Embezzlement': 9, 'Fel Assault': 10, 'Forgery & Counterfeiting': 11, 'Fraud': 12, 'GTMV': 13, 'Gambling': 14, 'Homicide': 15, 'Liquor Laws': 16, 'Offense Against Family/Children': 17, 'Property Damaged': 18, 'Prostitution': 19, 'Rape': 20, 'Robbery': 21, 'Sex Offenses': 22, 'Stolen Property': 23, 'Theft': 24, 'Traffic Violations': 25, 'Vandalism': 26, 'Weapons': 27}


OffenseYear: {2018: 0, 2019: 1, 2020: 2, 2021: 3, 2022: 4}


TimeBlock: {'Day': 0, 'Early Night': 1, 'Morning': 2, 'Night': 3}

In [27]:
# Drop last remaining unneeded columns
# Only remaining column that may be unnessary is OffenseDate
# It is useful to have a column in datetime format

cols = ['UCRdesc', 'OffenseYear', 'TimeBlock']

crime = crime.drop(columns=cols)

In [28]:
cols = ['CENSUS_TRACT', 'CENSUS_TRACT_GEOID', 'CENSUS_BLOCK_GROUP', 'CENSUS_BG_GEOID', 'CENSUS_BLOCK', 'CENSUS_BLOCK_GEOID']

# Loop through each column and count 'Not Located' occurrences
for col in cols:
    count_not_located = (crime[col] == 'Not Located').sum()
    print(f"'{col}' has {count_not_located} 'Not Located' entries")

'CENSUS_TRACT' has 1321 'Not Located' entries
'CENSUS_TRACT_GEOID' has 1321 'Not Located' entries
'CENSUS_BLOCK_GROUP' has 1321 'Not Located' entries
'CENSUS_BG_GEOID' has 1321 'Not Located' entries
'CENSUS_BLOCK' has 1321 'Not Located' entries
'CENSUS_BLOCK_GEOID' has 1321 'Not Located' entries

In [29]:
cols = ['CENSUS_TRACT_GEOID', 'CENSUS_BLOCK_GROUP', 'CENSUS_BG_GEOID', 'CENSUS_BLOCK_GEOID']
crime = crime.drop(columns=cols)

In [30]:
not_located_entries = crime[crime['CENSUS_BLOCK'] == 'Not Located']
crime = crime[~crime.index.isin(not_located_entries.index)]
crime.shape[0]

374721

In [32]:
not_located_entries = crime[crime['CENSUS_TRACT'] == 'Not Located']
crime = crime[~crime.index.isin(not_located_entries.index)]
crime.shape[0]

374721

In [33]:
# Important to note that we do not perform any feature scaling here
# This is because random forests are scale-invariant

crime.to_csv("crime_preprocessed_rf", index=False)